### ISSUE TITLE
site-title plugin throws on pages with no sidebar

### ISSUE THREAD

**Issue by LipGlossary** [zolk/docsify-breeze#64]
Particularly an issue on the customize/controls route. Here's the culprit:

https://github.com/zolk/docsify-breeze/blob/968a5dce92f3573a3b97e543ef6cddbe955083c2/docs/assets/plugins/site-title/site-title.js#L41-L43

Cheers!

**Comment by zolk** [comment]
Thanks! I noticed this recently but hadn't gotten around to looking into it yet. I'll plan on a fix.
